[package]
name = "scythe_bot"
version = "0.2.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.10.0"
ndarray = { version = "0.16.1", features = ["rayon"]}
rand = "0.9.2"
rayon = "1.11.0"
